// src/index.ts — public surface of the core engine package.
export * from "./types.js";
export { MemoryDB } from "./memory/db.js";
export { Ledger } from "./memory/ledger.js";
export { PatternCache } from "./memory/patternCache.js";
export { TaskHistory } from "./memory/taskHistory.js";
export { LearningLoop } from "./intelligence/learningLoop.js";
export { GraphBuilder, staticFallbackNodes, toNodeInputs, WIZARD_MODES } from "./intelligence/graphBuilder.js";
export type { WizardMode, GraphBuilderInput, BuildOutcome, FailureNote } from "./intelligence/graphBuilder.js";
export { Router, classifyComplexity } from "./routing/router.js";
export { TaskGraph } from "./taskGraph/graph.js";
export { CheckpointManager } from "./safety/checkpoint.js";
export { validate } from "./safety/validation.js";
export { FileLockManager } from "./engine/fileLock.js";
export { ExecutionEngine } from "./engine/executionEngine.js";
export { buildExecutorRegistry } from "./executors/index.js";
export * from "./adapters/index.js";
export { Wizard, WizardPlan, MAX_QUESTIONS } from "./wizard/wizard.js";
export type { WizardQuestion } from "./wizard/wizard.js";
export { loadForgeConfig, ensureForgeDirs, exampleConfigPath, defaultForgePaths } from "./config/loadConfig.js";
export type { ForgeConfig } from "./config/loadConfig.js";
export { probeAllProviders, applyProviderProbe } from "./config/providerProbe.js";
export type { ProviderStatus } from "./config/providerProbe.js";
export type { Capability } from './capabilities/Capability.js';
export type { CapabilityRequest } from './capabilities/CapabilityRequest.js';
export type { CapabilityResult } from './capabilities/CapabilityResult.js';
export type { CapabilityRegistry } from './capabilities/CapabilityRegistry.js';
export { InMemoryCapabilityRegistry } from './capabilities/InMemoryCapabilityRegistry.js';
export { vibeCodingCapability, fileManagementCapability, audioProcessingCapability } from './capabilities/builtins.js';
